# MCMC f90 org

* MCMC f90 library

From this page you can download source code for a Fortran 90 library statistical Markov chain Monte Carlo (MCMC) analyses of mathematical models. This code might be useful to you if you are already familiar with Fortran and MCMC.


This library provides tools to generate random walk Metropolis-Hastings MCMC chains using multivariate Gaussian proposal distribution. The covariance matrix of the proposal distribution can be adapted during the simulation according to adaptive schemes described in the references.

Check out my [[../mcmcstat/][Matlab MCMC Toolbox]]. It can be used to analyse the chains generated by this Fortran library.

* Downloads

 - Source code for the MCMC library is available from github: https://github.com/mjlaine/mcmcf90

The code is distributed under a MIT License and comes with no warranty. The documentation is minimal at the moment. Please read the source code for details of the algorithms used. Question and suggestions are welcome. If you find the code useful, it would be kind to acknowledge me in your research articles.

* References

# <<#ref:haario2006>>
H. Haario, M. Laine, A. Mira and E. Saksman, 2006.
/DRAM: Efficient adaptive MCMC/, 
Statistics and Computing *16*, pp. 339-354.
([[http://dx.doi.org/10.1007/s11222-006-9438-0][doi:10.1007/s11222-006-9438-0]])

# <<#ref:haario2001>>
H. Haario, E. Saksman and J. Tamminen, 2001.
/An adaptive Metropolis algorithm/
Bernoulli *7*, pp. 223-242.
([[http://dx.doi.org/10.2307/3318737][doi:10.2307/3318737]])


#+HTML: <hr>

# 
#+TITLE:     MCMC F90 library
#+AUTHOR:    Marko Laine
#+EMAIL:     marko.laine@fmi.fi
#+DESCRIPTION: Fortran 90 library for Markov chain Monte Carlo
#+KEYWORDS: MCMC, f90, adaptive mcmc
#+LANGUAGE:  en
#+HTML_LINK_HOME: http://helios.fmi.fi/~lainema/
#+HTML_LINK_UP: http://helios.fmi.fi/~lainema/
#+OPTIONS: num:nil toc:nil ^:{} creator:nil timestamp:t author:t
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />

# Local Variables:
# coding: utf-8
# mode: org
# eval: (visual-line-mode 1)
# eval: (auto-fill-mode -1)
# End:
